"""Fictional seed catalogue, merchant, customer, policies, and offers.

All names and SKUs are invented. Nothing is scraped from a live store.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any

from app.schemas.vocabulary import (
    ConstraintKind,
    DiscountType,
    PolicyCode,
    PolicyValueType,
    ProductCategory,
)

NOW = datetime(2026, 8, 1, tzinfo=timezone.utc)
OFFER_END = NOW + timedelta(days=365)

MERCHANT = {
    "ref_id": "MER-001",
    "name": "Lumen & Thread",
    "is_active": True,
}

CUSTOMER = {
    "ref_id": "CUS-001",
    "display_name": "Aanya Shah",
}

# Hero-session intent stored as explicit HARD vs SOFT rows (copied into Intent later).
CUSTOMER_PREFERENCES: list[dict[str, str]] = [
    {"ref_id": "PREF-001", "key": "budget_amount", "value": "2500", "kind": ConstraintKind.HARD.value},
    {"ref_id": "PREF-002", "key": "budget_currency", "value": "INR", "kind": ConstraintKind.HARD.value},
    {"ref_id": "PREF-003", "key": "occasion", "value": "farewell", "kind": ConstraintKind.SOFT.value},
    {"ref_id": "PREF-004", "key": "height", "value": "5ft2", "kind": ConstraintKind.SOFT.value},
    {"ref_id": "PREF-005", "key": "fit", "value": "relaxed_waist", "kind": ConstraintKind.SOFT.value},
    {"ref_id": "PREF-006", "key": "style", "value": "elegant", "kind": ConstraintKind.SOFT.value},
    {"ref_id": "PREF-007", "key": "style", "value": "youthful", "kind": ConstraintKind.SOFT.value},
    {"ref_id": "PREF-008", "key": "goal", "value": "complete_outfit", "kind": ConstraintKind.SOFT.value},
]

POLICIES: list[dict[str, Any]] = [
    {
        "ref_id": "POL-001",
        "code": PolicyCode.RESPECT_HARD_BUDGET.value,
        "value_type": PolicyValueType.BOOLEAN.value,
        "value_bool": True,
        "value_numeric": None,
        "value_text": None,
        "description": "Customer hard budget must be respected. Never upsell past it.",
    },
    {
        "ref_id": "POL-002",
        "code": PolicyCode.ONLY_REAL_INVENTORY.value,
        "value_type": PolicyValueType.BOOLEAN.value,
        "value_bool": True,
        "value_numeric": None,
        "value_text": None,
        "description": "Recommend and sell only real in-stock SKUs. Never invent products.",
    },
    {
        "ref_id": "POL-003",
        "code": PolicyCode.ONLY_AUTHORISED_OFFERS.value,
        "value_type": PolicyValueType.BOOLEAN.value,
        "value_bool": True,
        "value_numeric": None,
        "value_text": None,
        "description": "Only merchant-defined offers may be applied. No invented discounts.",
    },
    {
        "ref_id": "POL-004",
        "code": PolicyCode.NO_SILENT_BASKET_CHANGES.value,
        "value_type": PolicyValueType.BOOLEAN.value,
        "value_bool": True,
        "value_numeric": None,
        "value_text": None,
        "description": "Never silently change an approved basket. Re-approval is required.",
    },
    {
        "ref_id": "POL-005",
        "code": PolicyCode.APPROVAL_REQUIRED_BEFORE_CHECKOUT.value,
        "value_type": PolicyValueType.BOOLEAN.value,
        "value_bool": True,
        "value_numeric": None,
        "value_text": None,
        "description": "Customer approval of the exact basket version is required before checkout.",
    },
    {
        "ref_id": "POL-006",
        "code": PolicyCode.MIN_MARGIN_PERCENT.value,
        "value_type": PolicyValueType.NUMERIC.value,
        "value_bool": None,
        "value_numeric": Decimal("30.00"),
        "value_text": None,
        "description": "Minimum merchant margin percent after any authorised offer.",
    },
    {
        "ref_id": "POL-007",
        "code": PolicyCode.MAX_DISCOUNT_PERCENT.value,
        "value_type": PolicyValueType.NUMERIC.value,
        "value_bool": None,
        "value_numeric": Decimal("10.00"),
        "value_text": None,
        "description": "Maximum discount percent the agent may propose via authorised offers.",
    },
    {
        "ref_id": "POL-008",
        "code": PolicyCode.OFFER_STACKING_ALLOWED.value,
        "value_type": PolicyValueType.BOOLEAN.value,
        "value_bool": False,
        "value_numeric": None,
        "value_text": None,
        "description": "Offer stacking is prohibited.",
    },
]

OFFERS: list[dict[str, Any]] = [
    {
        "ref_id": "OFR-001",
        "name": "Campus pair 10",
        "discount_type": DiscountType.PERCENT.value,
        "discount_value": Decimal("10.00"),
        "min_basket_amount": Decimal("1500.00"),
        "max_discount_amount": Decimal("400.00"),
        "eligible_categories": [ProductCategory.TOPS.value, ProductCategory.TROUSERS.value],
        "eligible_product_ref_ids": [],
        "starts_at": NOW,
        "ends_at": OFFER_END,
        "stackable": False,
        "min_margin_percent": Decimal("30.00"),
        "is_active": True,
    },
    {
        "ref_id": "OFR-002",
        "name": "Soft save 8 on dresses",
        "discount_type": DiscountType.PERCENT.value,
        "discount_value": Decimal("8.00"),
        "min_basket_amount": Decimal("1000.00"),
        "max_discount_amount": Decimal("250.00"),
        "eligible_categories": [ProductCategory.DRESSES.value],
        "eligible_product_ref_ids": [],
        "starts_at": NOW,
        "ends_at": OFFER_END,
        "stackable": False,
        "min_margin_percent": Decimal("30.00"),
        "is_active": True,
    },
    {
        "ref_id": "OFR-003",
        "name": "Addon fifty",
        "discount_type": DiscountType.AMOUNT.value,
        "discount_value": Decimal("50.00"),
        "min_basket_amount": Decimal("0.00"),
        "max_discount_amount": Decimal("50.00"),
        "eligible_categories": [ProductCategory.ACCESSORIES.value],
        "eligible_product_ref_ids": ["PRD-012"],
        "starts_at": NOW,
        "ends_at": OFFER_END,
        "stackable": False,
        "min_margin_percent": Decimal("25.00"),
        "is_active": True,
    },
]

# 14 products, 24 variants. Mix of fit, budget, stock, and complete-look parts.
PRODUCTS: list[dict[str, Any]] = [
    {
        "ref_id": "PRD-001",
        "name": "Nira A-line Midi Dress",
        "category": ProductCategory.DRESSES.value,
        "description": "Burgundy A-line midi with a eased waist. Made for farewells that should feel elegant, not stiff.",
        "base_price": Decimal("1899.00"),
        "colour": "burgundy",
        "material": "crepe",
        "fit": "relaxed",
        "silhouette": "a-line",
        "length": "midi",
        "stretch": "low",
        "coverage": "standard",
        "occasion_tags": ["farewell", "dinner"],
        "style_tags": ["elegant", "youthful"],
        "margin_band": "MID",
        "margin_percent": Decimal("38.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-001-S", "size": "S", "colour": "burgundy", "price_override": None, "stock": 4},
            {"ref_id": "SKU-001-M", "size": "M", "colour": "burgundy", "price_override": None, "stock": 8},
            {"ref_id": "SKU-001-L", "size": "L", "colour": "burgundy", "price_override": None, "stock": 5},
        ],
    },
    {
        "ref_id": "PRD-002",
        "name": "Kavya Wrap Midi Dress",
        "category": ProductCategory.DRESSES.value,
        "description": "Navy wrap midi. Regular waist — useful as a fit comparison against relaxed silhouettes.",
        "base_price": Decimal("2199.00"),
        "colour": "navy",
        "material": "modal",
        "fit": "regular",
        "silhouette": "wrap",
        "length": "midi",
        "stretch": "medium",
        "coverage": "standard",
        "occasion_tags": ["farewell", "dinner"],
        "style_tags": ["elegant"],
        "margin_band": "MID",
        "margin_percent": Decimal("36.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-002-M", "size": "M", "colour": "navy", "price_override": None, "stock": 6},
            {
                "ref_id": "SKU-002-L",
                "size": "L",
                "colour": "navy",
                "price_override": Decimal("1999.00"),
                "stock": 4,
            },
        ],
    },
    {
        "ref_id": "PRD-003",
        "name": "Sable Bodycon Mini Dress",
        "category": ProductCategory.DRESSES.value,
        "description": "Fitted bodycon mini. Exists so relaxed-waist preferences can reject it without hallucinating SKUs.",
        "base_price": Decimal("1599.00"),
        "colour": "black",
        "material": "ponte",
        "fit": "bodycon",
        "silhouette": "bodycon",
        "length": "mini",
        "stretch": "high",
        "coverage": "low",
        "occasion_tags": ["party"],
        "style_tags": ["bold"],
        "margin_band": "MID",
        "margin_percent": Decimal("34.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-003-M", "size": "M", "colour": "black", "price_override": None, "stock": 5},
        ],
    },
    {
        "ref_id": "PRD-004",
        "name": "Aruna Relaxed Waist Trousers",
        "category": ProductCategory.TROUSERS.value,
        "description": "Soft-tailored trousers with a relaxed waist. Core piece for a ₹2,500 complete look.",
        "base_price": Decimal("1399.00"),
        "colour": "ink",
        "material": "viscose blend",
        "fit": "relaxed",
        "silhouette": "straight",
        "length": "full",
        "stretch": "low",
        "coverage": "standard",
        "occasion_tags": ["farewell", "office"],
        "style_tags": ["elegant", "youthful", "relaxed_waist"],
        "margin_band": "MID",
        "margin_percent": Decimal("35.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-004-S", "size": "S", "colour": "ink", "price_override": None, "stock": 0},
            {"ref_id": "SKU-004-M", "size": "M", "colour": "ink", "price_override": None, "stock": 14},
            {"ref_id": "SKU-004-L", "size": "L", "colour": "ink", "price_override": None, "stock": 6},
        ],
    },
    {
        "ref_id": "PRD-005",
        "name": "Tala Wide-Leg Jeans",
        "category": ProductCategory.TROUSERS.value,
        "description": "Wide-leg jeans. Higher price and low stock — a price-hesitation candidate with a cheaper sibling.",
        "base_price": Decimal("1699.00"),
        "colour": "indigo",
        "material": "denim",
        "fit": "relaxed",
        "silhouette": "wide-leg",
        "length": "full",
        "stretch": "low",
        "coverage": "standard",
        "occasion_tags": ["casual", "college"],
        "style_tags": ["youthful", "relaxed_waist"],
        "margin_band": "MID",
        "margin_percent": Decimal("32.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-005-M", "size": "M", "colour": "indigo", "price_override": None, "stock": 2},
            {"ref_id": "SKU-005-28", "size": "28", "colour": "indigo", "price_override": None, "stock": 0},
        ],
    },
    {
        "ref_id": "PRD-006",
        "name": "Jivika Straight Jeans",
        "category": ProductCategory.TROUSERS.value,
        "description": "Straight relaxed-fit jeans under ₹1,000. Cheaper alternative to Tala.",
        "base_price": Decimal("899.00"),
        "colour": "wash-blue",
        "material": "denim",
        "fit": "relaxed",
        "silhouette": "straight",
        "length": "full",
        "stretch": "medium",
        "coverage": "standard",
        "occasion_tags": ["casual", "college"],
        "style_tags": ["youthful", "relaxed_waist"],
        "margin_band": "HIGH",
        "margin_percent": Decimal("42.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-006-M", "size": "M", "colour": "wash-blue", "price_override": None, "stock": 10},
            {"ref_id": "SKU-006-L", "size": "L", "colour": "wash-blue", "price_override": None, "stock": 8},
        ],
    },
    {
        "ref_id": "PRD-007",
        "name": "Mira Soft Crepe Top",
        "category": ProductCategory.TOPS.value,
        "description": "Soft crepe top that completes the Aruna trousers look inside a ₹2,500 hard budget.",
        "base_price": Decimal("749.00"),
        "colour": "cream",
        "material": "crepe",
        "fit": "relaxed",
        "silhouette": "boxy",
        "length": "regular",
        "stretch": "none",
        "coverage": "standard",
        "occasion_tags": ["farewell", "office"],
        "style_tags": ["elegant", "youthful"],
        "margin_band": "HIGH",
        "margin_percent": Decimal("40.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-007-S", "size": "S", "colour": "cream", "price_override": None, "stock": 3},
            {"ref_id": "SKU-007-M", "size": "M", "colour": "cream", "price_override": None, "stock": 12},
            {"ref_id": "SKU-007-L", "size": "L", "colour": "cream", "price_override": None, "stock": 7},
        ],
    },
    {
        "ref_id": "PRD-008",
        "name": "Veda Structured Shirt",
        "category": ProductCategory.TOPS.value,
        "description": "Crisp shirt for office-adjacent farewell looks.",
        "base_price": Decimal("999.00"),
        "colour": "white",
        "material": "cotton poplin",
        "fit": "regular",
        "silhouette": "classic",
        "length": "regular",
        "stretch": "none",
        "coverage": "high",
        "occasion_tags": ["office", "farewell"],
        "style_tags": ["elegant"],
        "margin_band": "MID",
        "margin_percent": Decimal("37.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-008-M", "size": "M", "colour": "white", "price_override": None, "stock": 9},
        ],
    },
    {
        "ref_id": "PRD-009",
        "name": "Lumen Relaxed Overshirt",
        "category": ProductCategory.TOPS.value,
        "description": "Relaxed overshirt. Inventory-safe alternative when the denim jacket is too scarce or too costly.",
        "base_price": Decimal("1299.00"),
        "colour": "forest",
        "material": "twill",
        "fit": "relaxed",
        "silhouette": "oversized",
        "length": "regular",
        "stretch": "none",
        "coverage": "standard",
        "occasion_tags": ["casual", "college"],
        "style_tags": ["youthful"],
        "margin_band": "MID",
        "margin_percent": Decimal("33.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-009-M", "size": "M", "colour": "forest", "price_override": None, "stock": 18},
        ],
    },
    {
        "ref_id": "PRD-010",
        "name": "Neel Denim Jacket",
        "category": ProductCategory.TOPS.value,
        "description": "Classic denim jacket. Low stock. Pairing with ₹1,399 trousers would pressure a ₹2,500 hard budget.",
        "base_price": Decimal("1999.00"),
        "colour": "indigo",
        "material": "denim",
        "fit": "regular",
        "silhouette": "classic",
        "length": "regular",
        "stretch": "none",
        "coverage": "standard",
        "occasion_tags": ["casual"],
        "style_tags": ["youthful"],
        "margin_band": "LOW",
        "margin_percent": Decimal("28.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-010-M", "size": "M", "colour": "indigo", "price_override": None, "stock": 2},
        ],
    },
    {
        "ref_id": "PRD-011",
        "name": "Pebble Drop Earrings",
        "category": ProductCategory.ACCESSORIES.value,
        "description": "Small drop earrings. Completes the Aruna + Mira look at ₹299.",
        "base_price": Decimal("299.00"),
        "colour": "gold-tone",
        "material": "brass",
        "fit": "n/a",
        "silhouette": "drop",
        "length": "short",
        "stretch": "none",
        "coverage": "n/a",
        "occasion_tags": ["farewell", "dinner"],
        "style_tags": ["elegant", "youthful"],
        "margin_band": "HIGH",
        "margin_percent": Decimal("55.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-011-OS", "size": "OS", "colour": "gold-tone", "price_override": None, "stock": 20},
        ],
    },
    {
        "ref_id": "PRD-012",
        "name": "Kinara Mini Bag",
        "category": ProductCategory.ACCESSORIES.value,
        "description": "Mini bag at ₹499. Attach-rate temptation that can break a ₹2,500 hard budget.",
        "base_price": Decimal("499.00"),
        "colour": "burgundy",
        "material": "vegan leather",
        "fit": "n/a",
        "silhouette": "mini",
        "length": "n/a",
        "stretch": "none",
        "coverage": "n/a",
        "occasion_tags": ["farewell", "dinner"],
        "style_tags": ["elegant"],
        "margin_band": "HIGH",
        "margin_percent": Decimal("48.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-012-OS", "size": "OS", "colour": "burgundy", "price_override": None, "stock": 11},
        ],
    },
    {
        "ref_id": "PRD-013",
        "name": "Solstice Silk Scarf",
        "category": ProductCategory.ACCESSORIES.value,
        "description": "Printed scarf. Seeded out of stock for OOS exclusion tests.",
        "base_price": Decimal("399.00"),
        "colour": "dusty-rose",
        "material": "silk blend",
        "fit": "n/a",
        "silhouette": "scarf",
        "length": "n/a",
        "stretch": "none",
        "coverage": "n/a",
        "occasion_tags": ["farewell"],
        "style_tags": ["elegant"],
        "margin_band": "HIGH",
        "margin_percent": Decimal("50.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-013-OS", "size": "OS", "colour": "dusty-rose", "price_override": None, "stock": 0},
        ],
    },
    {
        "ref_id": "PRD-014",
        "name": "Asha Flare Midi Dress",
        "category": ProductCategory.DRESSES.value,
        "description": "Forest flare midi. Alternate farewell look when trousers sizes are missing.",
        "base_price": Decimal("899.00"),
        "colour": "forest",
        "material": "cotton sateen",
        "fit": "relaxed",
        "silhouette": "a-line",
        "length": "midi",
        "stretch": "none",
        "coverage": "standard",
        "occasion_tags": ["farewell", "dinner"],
        "style_tags": ["elegant", "youthful", "relaxed_waist"],
        "margin_band": "HIGH",
        "margin_percent": Decimal("41.00"),
        "is_active": True,
        "variants": [
            {"ref_id": "SKU-014-S", "size": "S", "colour": "forest", "price_override": None, "stock": 2},
            {"ref_id": "SKU-014-M", "size": "M", "colour": "forest", "price_override": None, "stock": 6},
        ],
    },
]


def all_variant_skus() -> list[str]:
    return [variant["ref_id"] for product in PRODUCTS for variant in product["variants"]]


def all_product_ref_ids() -> list[str]:
    return [product["ref_id"] for product in PRODUCTS]


OOS_SKUS = ("SKU-004-S", "SKU-005-28", "SKU-013-OS")
LOW_STOCK_SKUS = ("SKU-005-M", "SKU-010-M")
PRICE_OVERRIDE_SKU = "SKU-002-L"
HERO_TROUSER_SKU = "SKU-004-M"
HERO_TOP_SKU = "SKU-007-M"
HERO_EARRING_SKU = "SKU-011-OS"
COMPLETE_LOOK_TOTAL = Decimal("2447.00")  # 1399 + 749 + 299
