"""Closed vocabularies for MarginMind.

These sets are part of the architecture contract. Engines, API, frontend,
and eval must not invent values outside these enums.

Stdlib only in Milestone 0 (no Pydantic dependency installed yet).
"""

from enum import Enum


class BoundedAction(str, Enum):
    RECOMMEND = "RECOMMEND"
    BUILD_BASKET = "BUILD_BASKET"
    GUIDE_CONFIDENCE = "GUIDE_CONFIDENCE"
    SIMPLIFY_CHOICES = "SIMPLIFY_CHOICES"
    FIND_ALTERNATIVE = "FIND_ALTERNATIVE"
    REBUILD_BASKET = "REBUILD_BASKET"
    APPLY_AUTHORIZED_OFFER = "APPLY_AUTHORIZED_OFFER"
    NO_UPSELL = "NO_UPSELL"
    REQUEST_CHECKOUT = "REQUEST_CHECKOUT"
    STOP = "STOP"


class FrictionType(str, Enum):
    FIT_UNCERTAINTY = "FIT_UNCERTAINTY"
    STYLE_UNCERTAINTY = "STYLE_UNCERTAINTY"
    COLOUR_UNCERTAINTY = "COLOUR_UNCERTAINTY"
    BUDGET_MISMATCH = "BUDGET_MISMATCH"
    PRICE_HESITATION = "PRICE_HESITATION"
    SIZE_UNAVAILABLE = "SIZE_UNAVAILABLE"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    CHOICE_OVERLOAD = "CHOICE_OVERLOAD"
    BASKET_INCOMPLETE = "BASKET_INCOMPLETE"
    CATALOGUE_GAP = "CATALOGUE_GAP"
    CHECKOUT_HESITATION = "CHECKOUT_HESITATION"
    NONE = "NONE"


class AutonomyLevel(str, Enum):
    AUTO = "AUTO"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    NEVER_AUTONOMOUS = "NEVER_AUTONOMOUS"


class PolicyVerdict(str, Enum):
    PASS = "PASS"
    BLOCK = "BLOCK"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"


class ConstraintKind(str, Enum):
    HARD = "HARD"
    SOFT = "SOFT"


class PolicyCode(str, Enum):
    RESPECT_HARD_BUDGET = "RESPECT_HARD_BUDGET"
    ONLY_REAL_INVENTORY = "ONLY_REAL_INVENTORY"
    ONLY_AUTHORISED_OFFERS = "ONLY_AUTHORISED_OFFERS"
    NO_SILENT_BASKET_CHANGES = "NO_SILENT_BASKET_CHANGES"
    APPROVAL_REQUIRED_BEFORE_CHECKOUT = "APPROVAL_REQUIRED_BEFORE_CHECKOUT"
    MIN_MARGIN_PERCENT = "MIN_MARGIN_PERCENT"
    MAX_DISCOUNT_PERCENT = "MAX_DISCOUNT_PERCENT"
    OFFER_STACKING_ALLOWED = "OFFER_STACKING_ALLOWED"


class PolicyValueType(str, Enum):
    BOOLEAN = "BOOLEAN"
    NUMERIC = "NUMERIC"
    TEXT = "TEXT"


class DiscountType(str, Enum):
    PERCENT = "PERCENT"
    AMOUNT = "AMOUNT"


class ProductCategory(str, Enum):
    TOPS = "tops"
    TROUSERS = "trousers"
    DRESSES = "dresses"
    ACCESSORIES = "accessories"


class CheckoutState(str, Enum):
    DRAFT_BASKET = "DRAFT_BASKET"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED_UNVERIFIED = "APPROVED_UNVERIFIED"
    REVALIDATING = "REVALIDATING"
    READY_FOR_PAYMENT = "READY_FOR_PAYMENT"
    REVALIDATION_FAILED = "REVALIDATION_FAILED"
    ORDER_CREATED = "ORDER_CREATED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    VERIFIED = "VERIFIED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    ABANDONED = "ABANDONED"
